/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 head_of_david_but_with_hay.glb -t
Author: doubletwisted (https://sketchfab.com/dominikbargiel97)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/head-of-david-but-with-hay-585af747e89f4e78afda322c487a5059
Title: Head of David but with hay
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    meshNode_Material_u1_v1_0: THREE.Mesh
    meshNode_Material_u1_v1_0_1: THREE.Mesh
  }
  materials: {
    Material_u1_v1: THREE.MeshStandardMaterial
  }
};

export default function Model(props: JSX.IntrinsicElements['group']): JSX.Element {
  const { nodes, materials } = useGLTF('assets/michel_angelos.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[2.23, -22.65, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 16.79, 0.13]} rotation={[-Math.PI / 2, 0, 0]} scale={126.29}>
            <mesh geometry={nodes.meshNode_Material_u1_v1_0.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_1.geometry} material={materials.Material_u1_v1} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('assets/michel_angelos.glb');
